##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /chuitoeldebayamon
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh
include:
  - objects

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Chuito el de Bayamón
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: El decano de los cantores
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Esta exhibición digital reúne una selección de fotografías y documentos del archivo de Jesús Sánchez Erazo, conocido como Chuito el de Bayamón y una de las figuras más importantes de la música  puertorriqueña. A través de imágenes de sus presentaciones artísticas, momentos familiares, portadas discográficas y reconocimientos públicos, la muestra ofrece un recorrido por la trayectoria de un trovador cuya obra contribuyó a preservar y difundir la tradición de la décima y la cultura jíbara de Puerto Rico.<br><br>

El material de la muestra forma parte de un archivo mucho más amplio, compuesto por aproximadamente 18.000 documentos, entre manuscritos, grabaciones, fotografías y materiales impresos. Esta exhibición busca acercar al público a la vida y legado de Chuito. Así mismo, destaca la importancia de la preservación digital como una herramienta para ampliar el acceso al patrimonio cultural puertorriqueño.<br><br> This digital exhibition brings together a selection of photographs and documents from the archive of Jesús Sánchez Erazo, known as Chuito el de Bayamón, one of the most important figures in Puerto Rican music. Through images of his artistic performances, family moments, album covers and public recognitions, the exhibition offers a journey through the career of a troubadour whose work helped preserve and promote the tradition of the <em>décima</em> and Puerto Rico’s jíbaro culture.<br><br>

The materials featured in the exhibition are part of a much larger archive consisting of approximately 18,000 documents, including manuscripts, recordings, photographs and printed materials. This exhibition seeks to bring the Chuito's life and legacy to a wider audience. At the same time, it highlights the importance of digital preservation as a tool for expanding access to Puerto Rican cultural heritage."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Recovering the US Hispanic Literary Heritage Program

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: chuito_metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
